Controllers/AccountController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProfileMatching.Data;
using ProfileMatching.Models;
using ProfileMatching.Models.ViewModels;
using ProfileMatching.SD;

namespace ProfileMatching.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly AppDbContext _context;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager, AppDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    User user = new User()
                    {
                        Name = model.Fullname.Split(' ')[0],
                        Lastname = model.Fullname.Split(' ')[1],
                        Gender = model.Gender,
                        Email = model.Email,
                        Type = model.Type,
                        Role = SDClass.Simple,
                        EmailConfirmed = true,
                        NormalizedEmail = model.Email.ToUpper(),
                        LockoutEnabled = false,
                        UserName = model.Email,
                        imagePath = @"https://bootdey.com/img/Content/avatar/avatar6.png"
                    };

                    var result = await _userManager.CreateAsync(user, model.Password);

                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return RedirectToAction("Index", "Home");
                    }
                    else if (result.ToString().Contains("DuplicateUserName")) {
                        ModelState.AddModelError("Email", "This email is already registered");
                    }
                    else if (result.ToString().Contains("PasswordRequiresNonAlphanumeric,PasswordRequiresUpper"))
                    {
                        ModelState.AddModelError("Password", "This Password requires non alphanumeric characters and Upper characters");
                    }
                }

                return View(model);
            }
            catch (Exception e)
            {
                return Json(new {message = $"{e.Message}{e.InnerException?.Message}"});
            }
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = _context.Users.FirstOrDefault(x => x.Email == model.Email);
                    if(user == null)
                    {
                        ModelState.AddModelError("Email", "You need to register first");
                        return View(model);


                    }
                    var result = await _signInManager.PasswordSignInAsync(user.UserName, model.Password, false,
                        lockoutOnFailure: false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    string returnUrl = HttpContext.Request.Query["returnUrl"];
                    if (!String.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                        return Redirect(returnUrl);
                }

                return View();
            }
            catch (Exception e)
            {
                return Json(new {message = $"{e.Message}{e.InnerException?.Message}"});
            }
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Login", "Account");
        }
    }
}

Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NuGet.Protocol;
using ProfileMatching.Data;
using ProfileMatching.Models;
using ProfileMatching.Models.ViewModels;
using ProfileMatching.SD;

namespace ProfileMatching.Controllers;

[Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly UserManager<User> _userManager;
    private readonly AppDbContext _context;

    public HomeController(ILogger<HomeController> logger, UserManager<User> userManager, AppDbContext context)
    {
        _logger = logger;
        _userManager = userManager;
        _context = context;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var users = _userManager.Users.ToList();
        var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        List<UserViewModel> userViewModels = new List<UserViewModel>();
        var user = users.Find(x => x.Id == userId);


        var interactions = _context.Interactions.ToList();



        var userGender = user.Gender;
        var userType = user.Type;
        for (int i = 0; i < users.Count; i++)
        {
            var interaction = interactions.Find(x => (x.UserId1 == userId && x.UserId2 == users[i].Id));

            if (users[i].Id != userId && interaction== null && users[i].Type == userType)
            {
                if (userType == "business")
                {

                    userViewModels.Add(new UserViewModel()
                    {
                        Id = users[i].Id,
                        Name = users[i].Name,
                        Lastname = users[i].Lastname,
                        Height = users[i].Height,
                        Gender = users[i].Gender,
                        Age = users[i].Age,
                        Bio = users[i].Bio,
                        imagePath = users[i].imagePath
                    });

                }
                else if(userType == "normal" && userGender != users[i].Gender)
                {
                    userViewModels.Add(new UserViewModel()
                    {
                        Id = users[i].Id,
                        Name = users[i].Name,
                        Lastname = users[i].Lastname,
                        Height = users[i].Height,
                        Gender = users[i].Gender,
                        Age = users[i].Age,
                        Bio = users[i].Bio,
                        imagePath = users[i].imagePath
                    });
                }
            }
        }

        return View(userViewModels);
    }


    public IActionResult Swipes()
    {
        var matches = _context.Matches.ToList();
        var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        List<UserViewModel> userViewModels = new List<UserViewModel>();
        for (int i = 0; i < matches.Count; i++)
        {
            if (userId == matches[i].Userid1 )
            {
                var user = _userManager.Users.FirstOrDefault(x => x.Id == matches[i].Userid2);
                if (user != null)
                {
                    userViewModels.Add(new UserViewModel()
                    {
                        Id = user.Id,
                        Name = user.Name,
                        Lastname = user.Lastname,
                        Height = user.Height,
                        Gender = user.Gender,
                        Age = user.Age,
                        Bio = user.Bio,
                        imagePath = user.imagePath
                    });
                }

            }else if (userId == matches[i].Userid2) {
                var user = _userManager.Users.FirstOrDefault(x => x.Id == matches[i].Userid1);
                if (user != null)
                {
                    userViewModels.Add(new UserViewModel()
                    {
                        Id = user.Id,
                        Name = user.Name,
                        Lastname = user.Lastname,
                        Height = user.Height,
                        Gender = user.Gender,
                        Age = user.Age,
                        Bio = user.Bio,
                        imagePath = user.imagePath

                    });
                }
            }
        }

        return View(userViewModels);
    }

    [Authorize(Roles = SDClass.Admin)]
    public IActionResult Dashboard()
    {
        if (User.IsInRole(SDClass.Admin))
        {
            var users = _userManager.Users.ToList();
            List<UserViewModel> userViewModels = new List<UserViewModel>();
            for (int i = 0; i < users.Count; i++)
            {
                var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (users[i].Id != userId)
                {
                    userViewModels.Add(new UserViewModel()
                    {
                        Id = users[i].Id,
                        Name = users[i].Name,
                        Lastname = users[i].Lastname,
                        Type = users[i].Type,
                        Role = users[i].Role,
                        Height = users[i].Height,
                        Gender = users[i].Gender,
                        Age = users[i].Age,
                        Bio = users[i].Bio,
                    });
                }
            }

            return View(userViewModels);
        }
        else
        {
            string returnUrl = HttpContext.Request.Query["returnUrl"];
            if (!String.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                return Redirect(returnUrl);
        }

        return RedirectToAction("Index", "Home");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Account()
    {
        var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = _userManager.Users.FirstOrDefault(x => x.Id == userId);

        if (user != null)
        {
            UserViewModel model = new UserViewModel()
            {
                Id = user.Id,
                Name = user.Name,
                Lastname = user.Lastname,
                Email = user.Email,
                Type = user.Type,
                Role = user.Role,
                Height = user.Height,
                Gender = user.Gender,
                Age = user.Age,
                Bio = user.Bio,
                imagePath = user.imagePath
            };

            return View(model);
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Account(UserViewModel model)
    {
        
            
            if (model.Email != null && model.Fullname != null && model.Type != null && model.Age != 0 &&
                model.Height != 0 && model.Bio != null && model.Bio.Length <= 170 && model.Bio.Length >= 30)
            {
           
           
               var user = await _userManager.FindByEmailAsync(model.Email);
               var path = user.imagePath;

               if (model.Image != null)
                    {
                        var fullPath = Directory.GetCurrentDirectory() + @"/wwwroot/images/" + model.Image.FileName;
                         path = @"/images/" + model.Image.FileName;
                        using (FileStream stream = new FileStream(fullPath, FileMode.Create))
                        {
                            await model.Image.CopyToAsync(stream);
                            stream.Close();
                        }
                    }
               

                user.Name = model.Fullname.Split(' ')[0];
                user.Lastname = model.Fullname.Split(' ')[1];
                user.UserName = model.Email;
                user.Email = model.Email;
                user.Type = model.Type;
                user.Height = model.Height;
                user.Age = model.Age;
                user.Bio = model.Bio;
                user.imagePath = path;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
               
        }
        else
        {
            var user = await _userManager.FindByEmailAsync(model.Email);

            model.imagePath = user.imagePath;
            model.Name = model.Fullname.Split(' ')[0];
            model.Lastname = model.Fullname.Split(' ')[1];
            model.Gender = user.Gender;
            if (model.Age == 0)
            {
                ModelState.AddModelError("Age", "This cant be 0");

            }
            if (model.Height == 0)
            {
                ModelState.AddModelError("Height", "This cant be 0");

            }
            if (model.Bio?.Length >= 170 || model.Bio?.Length <= 30)
            {
                ModelState.AddModelError("Bio", "This cant be less than 30 and more than 170 characters");
            }
            ModelState.AddModelError("", "None of these values can be null!");
            return View("Account",model);
        }
        

        return RedirectToAction("Account", "Home");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

Controllers/InteractionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProfileMatching.Data;
using ProfileMatching.Models;
using ProfileMatching.Models.ViewModels;

namespace ProfileMatching.Controllers;

public class InteractionsController : Controller
{
    private readonly UserManager<User> _userManager;
    private AppDbContext _db;

    public InteractionsController(UserManager<User> userManager, AppDbContext db)
    {
        _userManager = userManager;
        _db = db;
    }

    [HttpPost]
    public void Add(string id, string interactionType)
    {
        var loggedUser = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        var person = _userManager.Users.FirstOrDefault(x => x.Id == id);

        var interaction = new Interactions()
        {
            Id = Guid.NewGuid().ToString(),
            UserId1 = loggedUser,
            UserId2 = id,
            InteractionDate = DateTime.Now,
            InteractionType = interactionType
        };

         _db.Interactions.Add(interaction);
         _db.SaveChanges();

        var result = _db.Interactions.FromSqlRaw("Exec GetInteractions @id1, @id2",
            new SqlParameter("@id1", id),
            new SqlParameter("@id2", loggedUser)).ToList();

        if (result.Count >= 2)
        {
            Match match = new Match()
            {
                Id = Guid.NewGuid().ToString(),
                Userid1 = loggedUser,
                Userid2 = id,
                match = true,
                matchDate = DateTime.Now
            };

            _db.Matches.Add(match);
            _db.SaveChanges();
        }
    }

    [HttpPost]
    public IActionResult Delete(string id)
    {
        if(id != null)
        {
            var user = _db.Users.FirstOrDefault(o => o.Id == id);
            var match = _db.Matches.ToList();
            for (var i = 0; i < match.Count; i++)
            {
                if (match[i].Userid1 == id || match[i].Userid2 == id)
                {
                    _db.Matches.Remove(match[i]);

                }
            }
            



            _db.Users.Remove(user);
            _db.SaveChanges();

            return RedirectToAction("Dashboard", "Home");

        }
        return RedirectToAction("Dashboard", "Home");
    }
}

Views/Home/Account.cshtml
@model ProfileMatching.Models.ViewModels.UserViewModel

@{
    Layout = "_Layout";
}


<div class="container">
    <div class="main-body">
        <h1 style="
    padding-top: 36px;
    padding-bottom: 36px;
   
">Account details</h1>

        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="@Model.imagePath" alt="Admin" class="img-fluid img-thumbnail p-1" width="550">
                            <div class="mt-3">
                                <h4>@Model.Name @Model.Lastname</h4>
                                <p class="text-secondary mb-1">@Model.Gender</p>
                                <p class="text-muted font-size-sm">@Model.Age y</p>
                            </div>
                        </div>
                        <hr class="my-4">
                    </div>
                </div>
            </div>

            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <form method="post" asp-controller="Home" asp-action="Account" enctype="multipart/form-data">
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <label asp-for="Fullname"></label>
                                    <input asp-for="@Model.Fullname" name="fullname" id="fullname" type="text" class="form-control" required value="@Model.Name @Model.Lastname">
                                    <span asp-validation-for="Fullname"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" asp-for="@Model.Email" required name="email" id="email" class="form-control" value="@Model.Email">
                                    <span asp-validation-for="Email"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Type</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input typeRadioButtons" onload="SetChecked(this)" type="radio" name="typeOptions" id="normalRadio" value="normal">
                                        <label class="form-check-label" for="normalRadio">Normal</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input typeRadioButtons" onload="SetChecked(this)" type="radio" name="typeOptions" id="businessmanRadio" value="business">
                                        <label class="form-check-label" for="businessmanRadio">Business</label>
                                    </div>
                                    <input type="text" asp-for="Type" name="type" value="@Model.Type" id="typeInput" hidden>
                                    <span asp-validation-for="Type"></span>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Age</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for="Age" name="age" id="age" type="text" class="form-control" value="@Model.Age">
                                    <span asp-validation-for="Age"></span>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Height</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for="Height" type="text" class="form-control" value="@Model.Height">
                                    <span asp-validation-for="Height"></span>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Bio</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for="Bio" type="text" class="form-control" value="@Model.Bio">
                                    <span asp-validation-for="Bio"></span>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Profile Picture</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for="Image" name="Image" type="file" id="file-input" class="form-control" accept="image/*">
                                    <img id="preview" src="#" alt="Image Preview" style="display: none;">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="submit" id="submitUpdate" class="btn btn-primary px-4" value="Save Changes">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<script>let normal = document.getElementById('normalRadio');
    let typeValue = document.getElementById('typeInput').value;

    if (typeValue === 'normal') {
        normal.checked = true;
    }
    else if (typeValue === 'business') {
        document.getElementById('businessmanRadio').checked = true;
    }

    let submit = document.getElementById('submitUpdate');
    submit.addEventListener('click', () => {
        let typeInput = document.getElementById('typeInput');
        let radioButtons = document.getElementsByClassName('typeRadioButtons');

        for (let i = 0; i < radioButtons.length; i++) {
            if (radioButtons[i].checked) {
                typeInput.value = radioButtons[i].value;
                console.log(radioButtons[i].value)
            }
        }
    })

    const fileInput = document.querySelector('#file-input');
    const preview = document.querySelector('#preview');

    fileInput.addEventListener('change', function () {
        const file = this.files[0];
        const reader = new FileReader();

        reader.addEventListener('load', function () {
            preview.src = reader.result;
            preview.style = "display: block;height: 560;margin-top: 30px;border: black 2px;border-style: solid;"
        });

        reader.readAsDataURL(file);
    });</script>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

Views/Home/Dashboard.cshtml
@model List<ProfileMatching.Models.ViewModels.UserViewModel>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@1.8.10/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <style>

        .main-content {
            margin-left: 200px;
            padding: 56px 20px 0 20px;
        }
    </style>
    <title>User Dashboard</title>
</head>
<body class="bg-gray-100">
    <nav class="bg-gray-900 shadow py-4">
        <div class="container mx-auto px-6">
            <a class="text-white text-2xl font-medium" href="#">User Dashboard</a>
        </div>
    </nav>

    <div class="main-content container mx-auto px-6 py-12">
        <table class="table-auto w-full">
            <thead>
                <tr class="bg-gray-800 text-white">
                    <th class="px-4 py-2">Name</th>
                    <th class="px-4 py-2">Gender</th>
                    <th class="px-4 py-2">Age</th>
                    <th class="px-4 py-2">Bio</th>
                    <th class="px-4 py-2">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr class="bg-white">
                        <td class="border px-4 py-2">@user.Name</td>
                        <td class="border px-4 py-2">@user.Gender</td>
                        <td class="border px-4 py-2">@user.Age</td>
                        <td class="border px-4 py-2">@user.Bio</td>
                        <td class="border px-4 py-2">
                            <form asp-action="Delete" asp-controller="Interactions" method="post">

                                <input type="hidden" name="id" value="@user.Id">

                                <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-lg delete-user" data-user-id="1">Delete</button>
                            </form>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</body>